- name: ensure nginx apt key exists
  sudo: yes
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: ensure nginx apt repo exists
  sudo: yes
  apt_repository: repo='deb http://nginx.org/packages/mainline/ubuntu/ {{ ansible_distribution_release }} nginx' state=present

- name: ensure nginx is installed
  sudo: yes
  apt: pkg=nginx state=present
